from datetime import timedelta, datetime
from enum import Enum

from temporalio import workflow
from temporalio.common import RetryPolicy

from models import OrderItem


class OrderStatus(str, Enum):
    INITIALIZING = "initializing"
    CREATED = "created"
    INVENTORY_RESERVED = "inventory_reserved"
    PAYMENT_PROCESSING = "payment_processing"
    PAYMENT_CONFIRMED = "payment_confirmed"
    PACKAGING = "packaging"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"
    FAILED = "failed"

# In your order_fulfillment.py
from dataclasses import dataclass
from typing import List, Optional
from decimal import Decimal

@dataclass
class TemporalOrderItem:
    product_id: int
    quantity: int
    price: Decimal

@dataclass
class OrderFulfillmentInput:
    user_id: int
    items: List[TemporalOrderItem]
    shipping_address: dict
    payment_method_id: str
    total_amount: Decimal
    order_id: str # eventually, order_id will be generated by create_order_activity

@dataclass
class OrderFulfillmentResult:
    order_id: str
    final_status: OrderStatus
    tracking_number: Optional[str] = None
    estimated_delivery: Optional[str] = None
    failure_reason: Optional[str] = None
    created_at: Optional[datetime] = None

with workflow.unsafe.imports_passed_through():
    from activities.order_activities import (
        update_order_status_activity,
        create_order_activity,
    )
    from process_payment import ProcessPaymentWorkflow

DEFAULT_RETRY_POLICY = RetryPolicy(
    maximum_attempts=3,
    initial_interval=timedelta(seconds=1),
    maximum_interval=timedelta(seconds=10),
    backoff_coefficient=2.0,
)

@workflow.defn
class OrderFulfillmentWorkflow:

    def __init__(self):
        self.current_order_status: OrderStatus = OrderStatus.INITIALIZING
        self.steps_completed = []
        self.is_paused = False

    @workflow.run
    async def order_fulfillment(self, user_id: str, input: OrderFulfillmentInput) -> OrderFulfillmentResult:
        workflow.logger.info(f"\n{'=' * 50}")
        workflow.logger.info(f"Initializing order for user: {user_id}, {len(input.items)} items")
        workflow.logger.info(f"{'=' * 50}\n")

        await workflow.execute_activity(
            update_order_status_activity,
            args=[input.order_id, self.current_order_status],
            start_to_close_timeout=timedelta(minutes=5),
            retry_policy=DEFAULT_RETRY_POLICY,
        )

        try:
            # Step 0: Create Order Record
            self.current_step = ("Creating Order")
            await self._wait_if_paused()
            await workflow.execute_activity(
                create_order_activity,
                args=[input],
                start_to_close_timeout=timedelta(minutes=5),
                retry_policy=DEFAULT_RETRY_POLICY
            )

            # Step 1: Reserve Inventory
            #
            # inventory_result = await workflow.execute_child_workflow(
            #     OrderFulfillmentWorkflow.order_fulfillment,
            #     args=[input.order_id, self.current_order_status],
            #     id=f"inventory-{input.order_id}",
            #     task_queue="inventory-tasks"
            # )

            # Step 2: Process Payment (your existing workflow)
            # Step 3: Package Order
            # Step 4: Ship Order
            # Step 5: Delivery Confirmation

            return OrderFulfillmentResult(
                order_id=input.order_id,
                final_status=OrderStatus.DELIVERED,
                # tracking_number=shipping_result.tracking_number,
                # estimated_delivery=delivery_result.estimated_delivery
            )

        except Exception as e:
            await self.compensate_order(input.order_id, str(e))
            return OrderFulfillmentResult(
                order_id=input.order_id,
                final_status=OrderStatus.FAILED,
                failure_reason=str(e)
            )

    async def compensate_order(self, order_id: str, reason: str):
        """Handle order failures with compensation"""
        # Release inventory, refund payment, etc.
        pass

    @workflow.signal
    async def pause(self):
        self.is_paused = True
        workflow.logger.info("▶️  Workflow RESUMED")

    @workflow.signal
    async def resume(self):
        self.is_paused = False
        workflow.logger.info("⏸️  Workflow PAUSED")

    @workflow.query
    def is_paused_query(self) -> bool:
        return self.is_paused

    async def _wait_if_paused(self):
        await workflow.wait_condition(lambda: not self.is_paused)
