services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dreamdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    platform: linux/amd64  # Add platform
    image: mmerrell/dream-demo-backend:sprint-2
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/dreamdemo
      SECRET_KEY: your-secret-key-here
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "8000:8000"

  frontend:
    platform: linux/amd64  # Add platform
    image: mmerrell/dream-demo-frontend:sprint-2
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://18.216.227.1:8000  # Fix to Elastic IP
      REACT_APP_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "3000:3000"

volumes:
  postgres_data: