from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import List, Optional

from sqlalchemy import Boolean, Column, Integer, String, Float, DateTime, func, ForeignKey
from sqlalchemy.orm import relationship
from database import Base


class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True, unique=True)
    description = Column(String)
    price = Column(Float(asdecimal=True))
    inventory_count = Column(Integer, default=0)
    image_url = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    is_active = Column(Boolean, default=True)

    orders = relationship("Order", back_populates="owner")

class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    status = Column(String, default="pending") # e.g., pending, paid, shipped, delivered

    owner = relationship("User", back_populates="orders")
    items = relationship("OrderItem", back_populates="order")

@dataclass
class TemporalOrderItem:
    product_id: int
    quantity: int
    price: Decimal

class OrderStatus(str, Enum):
    INITIALIZING = "initializing"
    CREATED = "created"
    INVENTORY_RESERVED = "inventory_reserved"
    PAYMENT_PROCESSING = "payment_processing"
    PAYMENT_CONFIRMED = "payment_confirmed"
    PACKAGING = "packaging"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"
    FAILED = "failed"

class OrderItem(Base):
    __tablename__ = "order_items"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"))
    product_id = Column(Integer, ForeignKey("products.id"))
    quantity = Column(Integer)
    price_at_purchase = Column(Float(asdecimal=True))

    order = relationship("Order", back_populates="items")
    product = relationship("Product")

@dataclass
class OrderFulfillmentInput:
    user_id: int  # Changed from customer_id to match create_order_activity
    items: List[TemporalOrderItem]
    shipping_address: dict
    payment_method_id: str
    total_amount: Decimal
    # order_id will be generated by create_order_activity

@dataclass
class OrderFulfillmentResult:
    order_id: str
    final_status: OrderStatus
    tracking_number: Optional[str] = None
    estimated_delivery: Optional[str] = None
    failure_reason: Optional[str] = None
    created_at: Optional[datetime] = None
